### ISSUE TITLE
Exception when executing maven plugin on toast-tk-examples

### ISSUE THREAD

**Issue by babebridou** [talan-labs/toast-tk-engine#110]
The same exception happens with our project, so I ran it on the example project.

PTPS12161@P76CLLCFC0O MINGW32 /d/git/toast/toast-tk-examples (master)
$ mvn install -PWEBAPP
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building toast-tk-examples 0.1.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- build-helper-maven-plugin:1.9.1:add-source (default) @ toast-tk-examples ---
[INFO] Source directory: D:\git\toast\toast-tk-examples\target\generated-sources\apt added.
[INFO] Source directory: D:\git\toast\toast-tk-examples\src\int\java added.
[INFO]
[INFO] --- toast-tk-maven-plugin:0.1.4-SNAPSHOT:download (default) @ toast-tk-examples ---
[INFO] Toast Tk Maven Plugin - Files will be generated in package null
[INFO] Toast Tk Maven Plugin - Connecting to -> http://localhost:9000
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
20:55:03.723 [main] ERROR io.toast.tk.core.rest.RestUtils - A JSONArray text must start with '[' at character 1
org.json.JSONException: A JSONArray text must start with '[' at character 1
        at org.json.JSONTokener.syntaxError(JSONTokener.java:410) ~[json-20090211.jar:?]
        at org.json.JSONArray.<init>(JSONArray.java:113) ~[json-20090211.jar:?]
        at org.json.JSONArray.<init>(JSONArray.java:157) ~[json-20090211.jar:?]
        at io.toast.tk.core.rest.RestUtils.downloadRepository(RestUtils.java:61) [toast-tk-rest-utils-0.1.4-SNAPSHOT.jar:?]
        at io.toast.tk.maven.plugin.DownloadScriptsMojo.execute(DownloadScriptsMojo.java:70) [toast-tk-maven-plugin-0.1.4-SNAPSHOT.jar:?]
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106) [maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863) [maven-embedder-3.3.9.jar:3.3.9]
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288) [maven-embedder-3.3.9.jar:3.3.9]
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199) [maven-embedder-3.3.9.jar:3.3.9]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) [plexus-classworlds-2.5.2.jar:?]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) [plexus-classworlds-2.5.2.jar:?]
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) [plexus-classworlds-2.5.2.jar:?]
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) [plexus-classworlds-2.5.2.jar:?]
[ERROR] Toast Tk Maven Plugin - Update cancelled !
[ERROR]
java.lang.NullPointerException
        at java.io.Writer.write(Writer.java:157)
        at io.toast.tk.maven.plugin.DownloadScriptsMojo.writeFile(DownloadScriptsMojo.java:196)
        at io.toast.tk.maven.plugin.DownloadScriptsMojo.execute(DownloadScriptsMojo.java:72)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by skokaina** [comment]
I wasn't able to reproduce it, here's the output I have on my side
[INFO] ------------------------------------------------------------------------
[INFO] Building toast-tk-examples 0.1.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- build-helper-maven-plugin:1.9.1:add-source (default) @ toast-tk-examples ---
[INFO] Source directory: /Users/blackbox/git/toast-tk-sample/toast-tk-examples/target/generated-sources/apt added.
[INFO] Source directory: /Users/blackbox/git/toast-tk-sample/toast-tk-examples/src/int/java added.
[INFO] 
[INFO] --- toast-tk-maven-plugin:0.1.4-SNAPSHOT:download (default) @ toast-tk-examples ---
[INFO] Toast Tk Maven Plugin - Files will be generated in package null
[INFO] Toast Tk Maven Plugin - Connecting to -> http://localhost:9000
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
[INFO] Copying 1 scenarios
[INFO] Toast Tk Maven Plugin - Update completed !

## [INFO] 

Could you please precise the configuration you're using ?
